/*
  Generates the golden vectors that hold src/lib/probe.ts and DeviceProbe.kt together.

  The site now predicts model throughput with the same arithmetic the app uses. Two
  implementations of one policy in two languages will drift - not on the day they are
  written, but on the day someone tunes the scoring weights in Kotlin and forgets that
  a web page also claims to be that policy. A site quoting the app's numbers while the
  app has moved on is worse than a site that never quoted them.

  So this script runs the TypeScript port over a fixed grid of profiles and writes every
  estimate, fit verdict and recommendation into the app's own test resources.
  DeviceProbeParityTest reads it back and asserts Kotlin produces the same values.
  Whichever side changes, the app's unit tests fail.

  The grid deliberately includes the awkward cases: a phone with no dotprod, a device too
  slow for anything in the catalog, and free-memory levels that straddle the TIGHT and
  TOO_BIG boundaries - the branches most likely to be edited and least likely to be
  noticed.

  ## Why TSV and not JSON

  The fixture is a table of numbers, and it has to be read by an Android unit test whose
  only test dependency is JUnit - `org.json` on that classpath is the stub, not a parser.
  A tab-separated file needs no parser on either side and, unlike pretty-printed JSON,
  produces a git diff that shows exactly which predictions moved when a constant changes.
  That diff is the point of the file.

  Run: npm run build:parity   (then run the app's unit tests)
*/
import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { ALL, estimate, assess, recommend, WORKLOADS } from "../src/lib/probe.ts";

const ROOT = path.resolve(import.meta.dirname, "..");
const DEST = path.resolve(
  ROOT, "..", "entity-arm", "app", "entity.android", "app", "src", "test", "resources"
);

const MB = 1024 * 1024;

/*
  Each profile is expressed on DeviceProbe's own scale - the arraycopy reading, not
  effective decode bandwidth - because that is what Profile takes. The anchor row is the
  reference device the constants were fitted to; the rest bracket it.
*/
const PROFILES = [
  { id: "anchor-cmf-phone-1", bandwidthGBs: 26.2, computeScore: 1.0, perfCores: 4, availableRamMb: 2304, flags: ["dotprod"] },
  { id: "anchor-more-free-ram", bandwidthGBs: 26.2, computeScore: 1.0, perfCores: 4, availableRamMb: 5120, flags: ["dotprod"] },
  { id: "budget-4gb", bandwidthGBs: 16.0, computeScore: 0.6, perfCores: 2, availableRamMb: 1536, flags: ["dotprod"] },
  { id: "no-dotprod", bandwidthGBs: 12.0, computeScore: 0.5, perfCores: 4, availableRamMb: 2048, flags: [] },
  { id: "flagship-16gb", bandwidthGBs: 72.0, computeScore: 2.4, perfCores: 6, availableRamMb: 9216, flags: ["dotprod", "i8mm", "sve"] },
  { id: "mid-i8mm", bandwidthGBs: 40.0, computeScore: 1.6, perfCores: 4, availableRamMb: 4096, flags: ["dotprod", "i8mm"] },
  // Straddles TOO_BIG for most of the catalog without excluding everything.
  { id: "cramped-1gb", bandwidthGBs: 20.0, computeScore: 0.8, perfCores: 4, availableRamMb: 1024, flags: ["dotprod"] },
  // Nothing in the catalog clears MIN_USABLE_DECODE here; recommend must return null.
  { id: "unusably-slow", bandwidthGBs: 0.2, computeScore: 0.05, perfCores: 2, availableRamMb: 2048, flags: [] },
];

/* Six decimals is far more precision than any estimate deserves and far less than a
   double carries, which is exactly what a parity fixture wants: policy differences show
   up, last-bit rounding differences do not. */
const n = (x) => x.toFixed(6);

const lines = [
  "# Golden vectors: the web port of DeviceProbe must agree with the Kotlin original.",
  "# Generated by entity-web `npm run build:parity` from src/lib/probe.ts. Do not hand-edit.",
  "# Read back by DeviceProbeParityTest. A diff here is a change in what the app recommends.",
  "#",
  "# profile   id  bandwidthGBs  computeScore  perfCores  availableRamBytes  flags(comma or -)",
  "# estimate  profileId  modelId  prefillToksPerS  decodeToksPerS  ttftSeconds  fit  reason",
  "# recommend profileId  workload  modelId(- if none)  runnerUp(- if none)  decode  prefill",
];

for (const raw of PROFILES) {
  const p = {
    bandwidthGBs: raw.bandwidthGBs,
    computeScore: raw.computeScore,
    perfCores: raw.perfCores,
    availableRamBytes: raw.availableRamMb * MB,
    flags: new Set(raw.flags),
  };

  lines.push(
    ["profile", raw.id, n(p.bandwidthGBs), n(p.computeScore), p.perfCores, p.availableRamBytes,
      raw.flags.length ? raw.flags.join(",") : "-"].join("\t")
  );

  for (const e of ALL) {
    const est = estimate(e, p);
    const a = assess(e, p.availableRamBytes, p.flags);
    lines.push(
      ["estimate", raw.id, e.id, n(est.prefillToksPerS), n(est.decodeToksPerS), n(est.ttftSeconds),
        a.fit, a.reason].join("\t")
    );
  }

  for (const w of WORKLOADS) {
    const r = recommend(p, w.id);
    lines.push(
      ["recommend", raw.id, w.id,
        r?.entry.id ?? "-", r?.runnerUp?.id ?? "-",
        r ? n(r.estimate.decodeToksPerS) : "-", r ? n(r.estimate.prefillToksPerS) : "-"].join("\t")
    );
  }
}

await mkdir(DEST, { recursive: true });
await writeFile(path.join(DEST, "probe-parity.tsv"), lines.join("\n") + "\n");
console.log(
  `parity fixture: ${PROFILES.length} profiles x ${ALL.length} models -> ${path.relative(ROOT, DEST)}/probe-parity.tsv`
);
